'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Award, Download, ExternalLink } from 'lucide-react';
import { api, usePoll, Loading, ErrorBox, Empty, Action, date, Badge } from './common';
import type { Notice, Certificate, User, Dashboard, Workshop, Attendance } from '@/lib/types';
import { AttendanceTable, downloadAttendance } from './workshop-detail';
export function Notifications(){const {data,error,refresh}=usePoll<Notice[]>('notifications');return <><div className="page-heading row-heading"><div><p className="eyebrow">STAY CONNECTED</p><h1>Notifications</h1><p>Workshop updates and announcements, as they happen.</p></div><Action className="secondary" onClick={async()=>{await api('notifications/all',{});await refresh();}}>Mark all as read</Action></div><section className="panel"><ErrorBox message={error}/>{!data?<Loading/>:data.length?data.map(n=><div className={`notification-row ${!n.readAt?'unread':''}`} key={n.id}><div><Link href={n.href} onClick={()=>void api(`notifications/${n.id}`,{}).then(refresh)}>{n.message}</Link><small>{new Date(n.createdAt).toLocaleString()}</small></div>{!n.readAt&&<Action className="small secondary" onClick={async()=>{await api(`notifications/${n.id}`,{});await refresh();}}>Mark read</Action>}</div>):<Empty title="You’re all caught up">New workshop notifications will appear automatically.</Empty>}</section></>;}
export function Certificates(){const {data,error}=usePoll<Certificate[]>('certificates');return <><div className="page-heading"><p className="eyebrow">VERIFIED LEARNING</p><h1>Certificates</h1><p>Your achievements, backed by verified workshop attendance.</p></div><ErrorBox message={error}/>{!data?<Loading/>:data.length?<div className="certificate-grid">{data.map(c=><article className="panel certificate-card" key={c.id}><div className="certificate-icon"><Award size={44}/></div><Badge tone="green">Certificate issued</Badge><h2>{c.workshopTitle}</h2><p>{c.participantName}</p><p className="subtle">{date(c.workshopDate)} · Attendance {c.attendancePercentage.toFixed(2)}%</p><div className="actions"><Link className="button gold" href={`/certificates/${c.id}`}>View certificate</Link><a className="button secondary" href={`/api/certificate/${c.id}/pdf?download=1`}><Download size={16}/>PDF</a><Link className="text-link" href={`/certificate/verify/${c.id}`}>Verify <ExternalLink size={15}/></Link></div></article>)}</div>:<section className="panel"><Empty title="Your certificates will appear here">Complete a workshop with at least 90% meeting attendance and verified QR attendance. Eligible certificates are issued when the organizer ends the session.</Empty><Link className="button" href="/workshops">Explore workshops</Link></section>}</>;}
export function CertificateView({id}:{id:string}){const {data:c,error}=usePoll<Certificate>(`certificate/${id}`,60_000);return <><div className="page-heading"><p className="eyebrow">SEMMOZHI CONNECT</p><h1>Certificate of participation</h1>{c&&<p>{c.participantName} · {c.workshopTitle}</p>}</div><ErrorBox message={error}/>{c&&<><div className="actions certificate-actions"><a className="button gold" href={`/api/certificate/${id}/pdf?download=1`}><Download size={18}/>Download PDF</a><Link className="button secondary" href={`/certificate/verify/${id}`}>Verify certificate</Link><a className="text-link" href={`/api/certificate/${id}/pdf`} target="_blank" rel="noopener noreferrer">Open full-size PDF ↗</a></div><iframe className="certificate-preview" title="Certificate PDF" src={`/api/certificate/${id}/pdf`}/></>}</>;}
export function Profile({user}:{user:User}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);return <><div className="page-heading"><h1>Your profile</h1><p>Keep your name correct for future certificates.</p></div><section className="panel form-panel"><form onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);setError('');setSaved(false);try{await api('profile',{name:fd.get('name'),department:fd.get('department')});setSaved(true);}catch(err){setError(err instanceof Error?err.message:'Unable to save profile.');}finally{setBusy(false);}}}><label>Full name<input name="name" required minLength={2} maxLength={100} defaultValue={user.name}/></label><label>Institution / department<input name="department" maxLength={120} defaultValue={user.department}/></label><label>Email<input value={user.email} readOnly/></label><ErrorBox message={error}/>{saved&&<p className="success">Profile saved. Existing issued certificates keep their original details.</p>}<button className="button" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form></section></>;}
export function Reports(){const {data:d,error,refresh}=usePoll<Dashboard>('dashboard');const [confirmation,setConfirmation]=useState('');return <><div className="page-heading"><p className="eyebrow">ADMINISTRATION</p><h1>Reports & system activity</h1><p>Recorded actions across your workshop platform.</p></div><ErrorBox message={error}/>{d&&<><section className="panel"><h2>Recent activity</h2>{d.activity.length?<div className="table-scroll"><table><thead><tr><th>Action</th><th>Details</th><th>Time</th></tr></thead><tbody>{d.activity.map(a=><tr key={a.id}><td>{a.action}</td><td>{a.detail}</td><td>{new Date(a.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>:<Empty title="No activity recorded yet"/>}</section>{d.demoMode&&<section className="panel reset-panel"><h2>Reset demo data</h2><p>Removes organizers and workshops created in demo mode, plus their registrations, attendance, QR challenges, notifications and certificates. Seeded Admin and Participant accounts are preserved.</p><label>Type RESET to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label>{confirmation==='RESET'&&<Action className="danger" onClick={async()=>{await api('reset',{confirmation});setConfirmation('');await refresh();}}>Reset demo data</Action>}</section>}</>}</>;}
export function WorkshopResources({mode}:{mode:'attendance'|'materials'}){const {data,error}=usePoll<Workshop[]>('workshops');const [selected,setSelected]=useState('');return <><div className="page-heading"><p className="eyebrow">YOUR WORKSHOP RESOURCES</p><h1>{mode==='attendance'?'Attendance':'Learning materials'}</h1><p>{mode==='attendance'?'Track verified participation in your workshops.':'Open a workshop to access its learning resources.'}</p></div><ErrorBox message={error}/>{!data?<Loading/>:data.length?<section className="panel"><label>Select a workshop<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose workshop</option>{data.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label>{selected&&(mode==='attendance'?<AttendanceResource id={selected}/>:<Link className="button" href={`/workshops/${selected}`}>Open workshop resources</Link>)}</section>:<section className="panel"><Empty title="No workshops available"/></section>}</>;}
function AttendanceResource({id}:{id:string}){const {data,error}=usePoll<Attendance>(`workshops/${id}/attendance`);return <><ErrorBox message={error}/>{data?<><AttendanceTable attendance={data}/><div className="actions"><Link className="button" href={`/workshops/${id}`}>Open workshop</Link><button className="button secondary" onClick={()=>downloadAttendance('workshop',data)}>Export CSV</button></div></>:<Loading/>}</>;}
