'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { Home, Users, CalendarDays, Award, Bell, LogOut, Menu, BookOpen, ChartNoAxesCombined, UserRound, X } from 'lucide-react';
import { api, usePoll } from './common';
import type { User, Notice } from '@/lib/types';
export function Shell({user,children}:{user:User;children:React.ReactNode}) {
  const pathname=usePathname(),router=useRouter(),[open,setOpen]=useState(false),[error,setError]=useState('');
  const {data:notices}=usePoll<Notice[]>('notifications');
  const base=`/${user.role.toLowerCase()}`;
  const links=user.role==='ADMIN'?[[Home,'Dashboard',base],[Users,'Organizers','/admin/organizers'],[CalendarDays,'Workshops','/workshops'],[Award,'Certificates','/certificates'],[ChartNoAxesCombined,'Reports & activity','/reports']]:[[Home,'Dashboard',base],[CalendarDays,user.role==='ORGANIZER'?'My workshops':'Explore workshops','/workshops'],[ChartNoAxesCombined,'Attendance','/attendance'],[BookOpen,'Learning materials','/materials'],[Award,'Certificates','/certificates'],[Bell,'Notifications','/notifications'],[UserRound,'Profile','/profile']];
  return <div className={`app-shell ${user.role==='ADMIN'?'admin-theme':''}`}><aside className={`sidebar ${open?'open':''}`}><Link href={base} className="brand"><strong>OSW<span>❧</span></strong><b>SEMMOZHI CONNECT</b><small>Learn · Participate · Preserve</small></Link><button className="mobile-close icon-button" aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button><nav>{links.map(([Icon,label,href])=>{const I=Icon as typeof Home;return <Link key={href as string} href={href as string} onClick={()=>setOpen(false)} className={pathname===href?'active':''}><I size={19}/>{label as string}</Link>;})}</nav><div className="sidebar-bottom"><p lang="ta">தமிழ் அறிவு<br/>உலகை இணைக்கும்</p><small>Knowledge in Tamil<br/>connects the world</small><button onClick={async()=>{try{await api('auth/logout',{});router.push('/login');router.refresh();}catch{setError('Sign out failed. Please try again.');}}}><LogOut size={18}/>Logout</button>{error&&<small role="alert">{error}</small>}</div></aside>{open&&<button className="sidebar-overlay" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<div className="app-content"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu/></button><div className="topbar-identity"><b>CENTRAL INSTITUTE OF CLASSICAL TAMIL</b><span>Heritage · Knowledge · Global Connect</span></div><div className="topbar-right"><Link href="/notifications" className="notification-bell" aria-label={`${notices?.filter(n=>!n.readAt).length??0} unread notifications`}><Bell size={22}/>{notices?.some(n=>!n.readAt)&&<i>{notices.filter(n=>!n.readAt).length}</i>}</Link><span className="avatar">{user.name.slice(0,1)}</span><div className="user-label"><b>{user.name}</b><small>{user.role.charAt(0)+user.role.slice(1).toLowerCase()}</small></div></div></header><main className="main-content">{children}</main><footer className="app-footer"><span><b>OSW</b> · Semmozhi Connect</span><span>A knowledge society for a brighter tomorrow</span></footer></div></div>;
}
